### ISSUE TITLE
ValueError in corpus.py

### ISSUE THREAD

**Issue by YuqiHuai** [MingfeiCheng/BehAVExplor#8]
When running scenario 1 via `./bazel-bin/BehAVExplor/main --config=/apollo/BehAVExplor/configs/s1.yaml`, I met

```
Traceback (most recent call last):
  File "/apollo/./bazel-bin/BehAVExplor/main.runfiles/apollo/BehAVExplor/main.py", line 150, in <module>
    fuzzer.loop(int(params['total_test_time'])) # seconds
  File "/apollo/./bazel-bin/BehAVExplor/main.runfiles/apollo/BehAVExplor/main.py", line 121, in loop
    corpus_seed_size, corpus_fail_size = input_corpus.add_seed(scenario_obj, scenario_recorder)
  File "/apollo/BehAVExplor/behavexplor/corpus.py", line 182, in add_seed
    feedback_coverage, min_coverage_distance = self.coverage_model.feedback_coverage_behavior(corpus_feature_behavior, is_fail)
ValueError: too many values to unpack (expected 2)
```

Looks like you have

```
# coverage.py
def feedback_coverage_behavior(self, x, is_fail):
        # @format x is the behavior extracted by the feature layer
        # @todo: modify this method
        ......
        return find_new_coverage, min_feedback, y_behavior

# corpus.py
feedback_coverage, min_coverage_distance = self.coverage_model.feedback_coverage_behavior(corpus_feature_behavior, is_fail)
```

The statement in `corpus.py` is expecting a 2-tuple to be returned, but `feedback_coverage_behavior` is returning a 3-tuple. I am not sure which one should be removed from the return statement. My guess is it would be fine if `y_behavior` is not returned, but I am not sure.

**Comment by MingfeiCheng** [comment]
Hi, Yuqi,

Thanks for your feedback. I have corrected the [line](https://github.com/MingfeiCheng/BehAVExplor/blob/dddfcf2c4c0895b5d5a80eb4eddd9d0f5003f52e/behavexplor/corpus.py#L182).

**Comment by YuqiHuai** [comment]
Thanks for fixing the issue!
